# Generated by Django 5.2.9 on 2026-01-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='characteristic',
            old_name='modiffied',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='modiffied',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='modiffied',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='footballclub',
            name='founded_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='home_stadium',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='owner_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='clubtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clubtype'),
        ),
    ]
